services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:8080/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [foodnet]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    networks: [foodnet]

networks:
  foodnet: {}
