FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# non-root user
RUN adduser --disabled-password --gecos "" appuser && chown -R appuser /app

# (optionale) deps
COPY worker/requirements.txt /tmp/requirements.txt
RUN [ -s /tmp/requirements.txt ] || echo "" > /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# code
COPY worker/ /app/

USER appuser
CMD ["python","/app/worker.py"]
